<NumberBtn>:
    font_size: 35
    background_normal: ''
    background_down: ''
    background_color: [0.3, 0.3, 0.3, 1]
    foreground_color: [1, 1, 1, 1]

<SpecialBtn>:
    font_size: 35
    background_normal: ''
    background_down: ''
    background_color: [1, 0.6, 0, 0.9]
    foreground_color: [1, 1, 1, 1]

<OperatorBtn>:
    font_size: 35
    background_normal: ''
    background_down: ''
    background_color: [1, 0.6, 0, 0.9]
    foreground_color: [1, 1, 1, 1]
    group: "operators"

<CalcLayout>:
    id: calculator
    display: _display
    clear_btn: _clear_btn
    orientation: "vertical"
    spacing: 5

    BoxLayout:
        Label:
            id: _display
            text: '0'
            font_size: 54
            halign: "right"
            multiline: False
            text_size: calculator.width - 50, None
            background_color: [0.1, 0.1, 0.1, 1]
            foreground_color: [1, 1, 1, 1]

    BoxLayout:
        spacing: 5

        SpecialBtn:
            id: _clear_btn
            text: "AC"
            size_hint_x: 51
            on_press: calculator.clear()
        NumberBtn:
            text: "%"
            size_hint_x: 25
            on_press: calculator.add(self.text)
        SpecialBtn:
            text: "+/-"
            size_hint_x: 25
            on_press: calculator.inverse()

    BoxLayout:
        spacing: 5

        NumberBtn:
            text: "7"
            on_press: calculator.add(self.text)
        NumberBtn:
            text: "8"
            on_press: calculator.add(self.text)
        NumberBtn:
            text: "9"
            on_press: calculator.add(self.text)
        OperatorBtn:
            text: "+"
            
    BoxLayout:
        spacing: 5

        NumberBtn:
            text: "4"
            on_press: calculator.add(self.text)
        NumberBtn:
            text: "5"
            on_press: calculator.add(self.text)
        NumberBtn:
            text: "6"
            on_press: calculator.add(self.text)
        OperatorBtn:
            text: "-"
            font_size: 50

    BoxLayout:
        spacing: 5

        NumberBtn:
            text: "1"
            on_press: calculator.add(self.text)
        NumberBtn:
            text: "2"
            on_press: calculator.add(self.text)
        NumberBtn:
            text: "3"
            on_press: calculator.add(self.text)
        OperatorBtn:
            text: "×"

    BoxLayout:
        spacing: 5

        NumberBtn:
            text: "."
            font_size: 80
            on_press: calculator.add(self.text)
        NumberBtn:
            text: "0"
            on_press: calculator.add(self.text)
        SpecialBtn:
            text: "="
            on_press: calculator.calc()
        OperatorBtn:
            text: "÷"